# Generated by Django 3.1.1 on 2020-10-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0004_auto_20201001_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('maximo_descuento', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('anulado', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
