# Generated by Django 3.1.1 on 2020-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'Medicamentos'), (2, 'Droga blanca'), (3, 'Perfumes'), (4, 'Accesorios')], default=1, verbose_name='Grupo'),
        ),
    ]
