# Generated by Django 3.1.1 on 2020-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20201002_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bodegas',
            field=models.ManyToManyField(to='item.Bodegas'),
        ),
    ]
