# Generated by Django 3.1.1 on 2020-10-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_bodegas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['codigo'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
