# Generated by Django 3.1.1 on 2020-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0003_auto_20201001_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Apellido')),
                ('job', models.CharField(choices=[('ING', 'Ingeniero'), ('CON', 'Contador'), ('VEN', 'Vendedor'), ('OBR', 'Obrero')], max_length=3, verbose_name='Profesión')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
