# Generated by Django 3.1.1 on 2020-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20201001_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Foto'),
        ),
    ]
